name: C/C++ CI on Windows (vs2019)

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: windows-2019
    name: Build

    steps:

    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Cache Windows Release output (vs2019)
      id: cache-Win-Release
      uses: actions/cache@v2
      with:
        path: Solutions/out/Release
        key: ${{ runner.os }}-vs2019-${GITHUB_REF#refs/heads/}
        restore-keys: |
          ${{ runner.os }}-${GITHUB_REF#refs/heads/}
          ${{ runner.os }}-master

    - name: Setup Tools
      shell: cmd
      run: tools\setup-buildtools.cmd

    - name: Build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_PULL_TOKEN: ${{ secrets.GIT_PULL_TOKEN }}
        SKIP_ARM_BUILD: 1
        SKIP_ARM64_BUILD: 1
        PlatformToolset: v142
      shell: cmd
      run: build-all.bat
