name: C/C++ CI on Linux and Mac

on:
  push:
    branches:
    - master
    - release/*
    - buildme/*
  pull_request:
    branches:
    - master
  schedule:
  - cron: 0 2 * * 1-5

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        config: [release, debug]
        os: [ubuntu-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Test ${{ matrix.os }} ${{ matrix.config }}
      run: ./build-tests.sh ${{ matrix.config }}
